SELECT TEMP.CUSTOMER_ID
FROM
(
    SELECT DISTINCT CUSTOMER_ID,PRODUCT_KEY
    FROM Customer
) AS TEMP
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) = (
    SELECT COUNT(PRODUCT_KEY)
    FROM Product
)
ORDER BY CUSTOMER_ID;
