SELECT A.CUSTOMER_ID,COUNT(A.CUSTOMER_ID) AS COUNT_NO_TRANS
FROM Visits AS A
LEFT JOIN Transactions AS B
ON A.VISIT_ID = B.VISIT_ID
WHERE TRANSACTION_ID IS NULL
GROUP BY CUSTOMER_ID
ORDER BY 
COUNT_NO_TRANS DESC;