# Write your MySQL query statement below
SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM
(SELECT 
A.EMPLOYEE_ID AS EMPLOYEE_ID, 
CASE WHEN COUNT(A.EMPLOYEE_ID) = 1 
THEN A.DEPARTMENT_ID
ELSE (
  SELECT B.DEPARTMENT_ID FROM Employee AS B WHERE B.EMPLOYEE_ID = A.EMPLOYEE_ID AND B.PRIMARY_FLAG = 'Y'
  ) END AS DEPARTMENT_ID
FROM Employee AS A
GROUP BY A.EMPLOYEE_ID
ORDER BY A.EMPLOYEE_ID) AS TEMP_TABLE 
WHERE DEPARTMENT_ID IS NOT NULL;