# Write your MySQL query statement below
SELECT CASE WHEN COUNT(NUM) = 0 THEN NULL ELSE NUM END AS NUM
FROM
(
  SELECT NUM
  FROM MyNumbers
  GROUP BY NUM
  HAVING COUNT(NUM) = 1
  ORDER BY NUM DESC
  LIMIT 1
) AS TEMP;