SELECT A.MACHINE_ID, ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP),3) AS PROCESSING_TIME
FROM Activity AS A
JOIN Activity AS B
ON  (A.MACHINE_ID = B.MACHINE_ID AND A.PROCESS_ID = B.PROCESS_ID AND (A.ACTIVITY_TYPE = 'start' AND B.ACTIVITY_TYPE = 'end'))
GROUP BY A.MACHINE_ID
ORDER BY A.MACHINE_ID;
#A.MACHINE_ID,ROUND(AVG(B.TIMESTAMP-A.TIMESTAMP),3)