SELECT TEMP.PROJECT_ID, ROUND(AVG(TEMP.EXPERIENCE_YEARS), 2) AS AVERAGE_YEARS
FROM (
    SELECT P.PROJECT_ID AS PROJECT_ID, E.EXPERIENCE_YEARS AS EXPERIENCE_YEARS
    FROM Project AS P
    JOIN Employee AS E ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
) AS TEMP
GROUP BY TEMP.PROJECT_ID
ORDER BY TEMP.PROJECT_ID;
